### ISSUE TITLE
Running the example json gave me a few errors

### ISSUE THREAD

**Issue by mocmocmoc** [kijai/ComfyUI-VoiceCraft#1]
Installed through ComfyUI-Manager's "install from git". Then installed "Missing Custom Nodes". Got a bunch of errors.
.

First error from _VHS_VideoCombine_ node

    Failed to validate prompt for output 4:
    * (prompt):
      - Return type mismatch between linked nodes: frame_rate, INT != FLOAT
    * VHS_VideoCombine 4:
      - Return type mismatch between linked nodes: frame_rate, INT != FLOAT
    Output will be ignored

I unlink _frame_rate_ input and create a new node by double clicking it. This fix the problem.
.

Second error from _CreateTextMask_ node.

     Error occurred when executing CreateTextMask:

    'FreeTypeFont' object has no attribute 'getsize'

    File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes\nodes.py", line 717, in createtextmask
    word_width = font.getsize(word)[0]
    ^^^^^^^^^^^^

I can bypass it by loading a random image but then,
.

I get third error from _audio_tensor_enhance_ node

```
Error occurred when executing audio_tensor_enhance:

No module named 'df'

File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VoiceCraft\nodes.py", line 472, in process
from df.enhance import enhance, init_df, resample
```

It still generated a wav in \ComfyUI-VoiceCraft\temp but only one part.

**Comment by djdookie** [comment]
> Error occurred when executing audio_tensor_enhance:
> No module named 'df'

Also got this error.

**Comment by djdookie** [comment]
I Identified df.enhance as deepfilternet.
You can solve it with CompyUI Manager, click "install pip packages", then insert "deepfilternet".
I guess we could add that missing package to the custom nodes requirements.txt to prevent this issue.

**Comment by mocmocmoc** [comment]
Also fixed 
_'FreeTypeFont' object has no attribute 'getsize'_ 
by install pip packages _Pillow<=9.5.0_

**Comment by kijai** [comment]
> I Identified df.enhance as deepfilternet. You can solve it with CompyUI Manager, click "install pip packages", then insert "deepfilternet". I guess we could add that missing package to the custom nodes requirements.txt to prevent this issue.

Yeah this was my bad, simply forgot it, it's been added to reqs now.

**Comment by kijai** [comment]
At some point VHS nodes frame_rate input changed from INT to FLOAT, fixed that in the example workflows. Also fixed the pillow fontsize for KJNodes, and added the deepfilternet to reqs. I noticed it didn't install with just pip when using python 3.12, I had to additionally install rustup: https://rustup.rs/
